---
- name: Install
  ansible.builtin.package:
    name:
      - zsh
    state: latest
  become: no

- name: Set default
  user:
    name: "{{ ansible_env['USER'] }}"
    shell: /bin/zsh
  become: yes

